### PR TITLE
Add AWS Connector and Tests

### PR DESCRIPTION
**Pull request by johnnorton**

### CODE REVIEW

**Comment by rssnyder** [comment]
awesome! module works for me, but the docs need to be cleaned up (referencing azure vs aws).

**Comment by lorenyeung** [comment]
LGTM; verified that delegate_selectors at root level does not apply, and only takes effect at credentials level

**Review by lorenyeung — APPROVED** [review]
lgtm

**Comment by goodrum-harness** [comment]
Had to close this request due to issues with merging and resubmitted in a new [PR #5 ](https://github.com/harness-community/terraform-harness-connectors/pull/5)

**Pull request closed without merging**
